version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.11.13-management
    build:
      context: ./rabbit
    volumes:
      - ./.data/rabbitmq/:/var/lib/rabbitmq/mnesia
    environment:
      - RABBITMQ_USER=rabbit
      - RABBITMQ_PASSWORD=mq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - test_network


networks:
  test_network:
    name: test_network
